# Generated by Django 5.1 on 2024-08-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField()),
                ('long_description', models.TextField()),
                ('career_level', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('work_mode', models.CharField(max_length=100)),
                ('contract_location', models.CharField(max_length=255)),
                ('application_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField()),
                ('long_description', models.TextField()),
                ('career_level', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('work_mode', models.CharField(max_length=100)),
                ('contract_location', models.CharField(max_length=255)),
                ('application_link', models.URLField()),
            ],
        ),
    ]
