# Generated by Django 5.1.1 on 2024-09-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, db_column='Department', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(db_column='Employment_type', default='Full-time', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.AutoField(default='Full-time', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='application_link',
            field=models.URLField(db_column='application_link'),
        ),
        migrations.AlterField(
            model_name='job',
            name='career_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='contract_location',
            field=models.CharField(db_column='contract_location', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='long_description',
            field=models.TextField(db_column='long_description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='posting_date',
            field=models.DateField(db_column='Post_date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(db_column='Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
