# Generated by Django 5.1.1 on 2024-09-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_id_job_department_job_employment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='department',
        ),
    ]
